import json
import random
import copy

# ==========================================
# LEVEL 1 DATASETS (EASY)
# ==========================================

# --- SYNONYMS L1 (55 items) ---
synonyms_l1 = [
    ("Happy", "Joyful", ["Sad", "Angry", "Tired"]),
    ("Big", "Large", ["Small", "Tiny", "Weak"]),
    ("Fast", "Quick", ["Slow", "Lazy", "Late"]),
    ("Beautiful", "Pretty", ["Ugly", "Scary", "Dirty"]),
    ("Start", "Begin", ["Stop", "End", "Finish"]),
    ("End", "Finish", ["Start", "Begin", "Open"]),
    ("Hard", "Difficult", ["Easy", "Soft", "Simple"]),
    ("Rich", "Wealthy", ["Poor", "Weak", "Sick"]),
    ("Smart", "Clever", ["Stupid", "Dumb", "Slow"]),
    ("Kind", "Nice", ["Mean", "Rude", "Cruel"]),
    ("Angry", "Mad", ["Happy", "Calm", "Glad"]),
    ("Correct", "Right", ["Wrong", "False", "Bad"]),
    ("Wrong", "Incorrect", ["Right", "True", "Good"]),
    ("Present", "Gift", ["Box", "Toy", "Money"]),
    ("House", "Home", ["Car", "Park", "School"]),
    ("Listen", "Hear", ["See", "Smell", "Taste"]),
    ("Speak", "Talk", ["Walk", "Run", "Sleep"]),
    ("Cry", "Weep", ["Laugh", "Smile", "Sing"]),
    ("Laugh", "Giggle", ["Cry", "Scream", "Yell"]),
    ("Small", "Little", ["Big", "Huge", "Tall"]),
    ("Cold", "Chilly", ["Hot", "Warm", "Dry"]),
    ("Hot", "Warm", ["Cold", "Cool", "Wet"]),
    ("Strong", "Powerful", ["Weak", "Soft", "Small"]),
    ("Brave", "Courageous", ["Scared", "Fearful", "Cowardly"]),
    ("Scared", "Afraid", ["Brave", "Happy", "Calm"]),
    ("Jump", "Leap", ["Sit", "Sleep", "Walk"]),
    ("Run", "Sprint", ["Walk", "Crawl", "Sit"]),
    ("Choose", "Pick", ["Drop", "Throw", "Leave"]),
    ("Help", "Assist", ["Hurt", "Stop", "Block"]),
    ("Make", "Create", ["Destroy", "Break", "Kill"]),
    ("Break", "Smash", ["Fix", "Repair", "Build"]),
    ("Fix", "Repair", ["Break", "Hurt", "Cut"]),
    ("Neat", "Tidy", ["Messy", "Dirty", "Ugly"]),
    ("Messy", "Dirty", ["Clean", "Neat", "New"]),
    ("New", "Fresh", ["Old", "Stale", "Used"]),
    ("Old", "Ancient", ["New", "Young", "Fresh"]),
    ("Quiet", "Silent", ["Loud", "Noisy", "Busy"]),
    ("Loud", "Noisy", ["Quiet", "Calm", "Soft"]),
    ("Funny", "Amusing", ["Boring", "Sad", "Serious"]),
    ("Sad", "Unhappy", ["Glad", "Joyful", "Excited"]),
    ("Job", "Work", ["Play", "Fun", "Rest"]),
    ("Trip", "Journey", ["Stay", "Home", "Sleep"]),
    ("Sick", "Ill", ["Well", "Healthy", "Strong"]),
    ("Fat", "Chubby", ["Thin", "Skinny", "Slim"]),
    ("Thin", "Slim", ["Fat", "Heavy", "Big"]),
    ("Tall", "High", ["Short", "Low", "Small"]),
    ("Short", "Tiny", ["Tall", "Big", "High"]),
    ("Ask", "Question", ["Answer", "Tell", "Say"]),
    ("Answer", "Reply", ["Ask", "Question", "Ignore"]),
    ("Allow", "Let", ["Stop", "Ban", "Hold"]),
    ("Keep", "Hold", ["Drop", "Throw", "Give"]),
    ("Give", "Offer", ["Take", "Keep", "Steal"]),
    ("Get", "Receive", ["Give", "Send", "Lose"]),
    ("Want", "Desire", ["Hate", "Refuse", "Stop"]),
    ("Try", "Attempt", ["Give up", "Quit", "Stop"])
]

# --- ANTONYMS L1 (55 items) ---
antonyms_l1 = [
    ("Hot", "Cold", ["Warm", "Boiling", "Sunny"]),
    ("Up", "Down", ["Left", "Right", "High"]),
    ("Left", "Right", ["Up", "Down", "Center"]),
    ("Happy", "Sad", ["Angry", "Mad", "Glad"]),
    ("Big", "Small", ["Huge", "Giant", "Large"]),
    ("Fast", "Slow", ["Quick", "Rapid", "Speed"]),
    ("Win", "Lose", ["Draw", "Play", "Game"]),
    ("Day", "Night", ["Sun", "Moon", "Star"]),
    ("Black", "White", ["Grey", "Red", "Blue"]),
    ("Hard", "Soft", ["Difficult", "Tough", "Rough"]),
    ("Rich", "Poor", ["Wealthy", "Money", "Gold"]),
    ("Tall", "Short", ["High", "Big", "Long"]),
    ("Full", "Empty", ["Half", "All", "None"]),
    ("Start", "Stop", ["Begin", "Go", "Move"]),
    ("Open", "Close", ["Shut", "Lock", "Door"]),
    ("In", "Out", ["On", "Off", "Under"]),
    ("On", "Off", ["In", "Out", "Up"]),
    ("Wet", "Dry", ["Water", "Rain", "Soak"]),
    ("Clean", "Dirty", ["Wash", "Soap", "Bath"]),
    ("New", "Old", ["Fresh", "Young", "Modern"]),
    ("Young", "Old", ["New", "Baby", "Child"]),
    ("Good", "Bad", ["Nice", "Well", "Fine"]),
    ("Love", "Hate", ["Like", "Care", "Friend"]),
    ("Friend", "Enemy", ["Pal", "Buddy", "Mate"]),
    ("Buy", "Sell", ["Shop", "Pay", "Cost"]),
    ("Give", "Take", ["Get", "Have", "Hold"]),
    ("Push", "Pull", ["Shove", "Move", "Lift"]),
    ("Sit", "Stand", ["Lie", "Walk", "Run"]),
    ("Laugh", "Cry", ["Smile", "Joke", "Fun"]),
    ("True", "False", ["Right", "Correct", "Real"]),
    ("Right", "Wrong", ["Left", "Correct", "True"]),
    ("Before", "After", ["Now", "Then", "When"]),
    ("Near", "Far", ["Close", "Here", "Next"]),
    ("High", "Low", ["Tall", "Top", "Up"]),
    ("First", "Last", ["Second", "Third", "End"]),
    ("Best", "Worst", ["Good", "Better", "Bad"]),
    ("More", "Less", ["Many", "Much", "Lot"]),
    ("Always", "Never", ["Sometime", "Often", "Rare"]),
    ("Easy", "Difficult", ["Hard", "Simple", "Basic"]),
    ("Heavy", "Light", ["Big", "Fat", "Huge"]),
    ("Top", "Bottom", ["High", "Up", "Peak"]),
    ("Float", "Sink", ["Fly", "Swim", "Sail"]),
    ("Rough", "Smooth", ["Hard", "Bumpy", "Soft"]),
    ("Sharp", "Dull", ["Pointy", "Cut", "Knife"]),
    ("Tight", "Loose", ["Hard", "Firm", "Stuck"]),
    ("Safe", "Dangerous", ["Good", "Fine", "Okay"]),
    ("Same", "Different", ["Like", "Twin", "Equal"]),
    ("Quiet", "Loud", ["Silent", "Calm", "Still"]),
    ("Wide", "Narrow", ["Big", "Fat", "Thick"]),
    ("Thick", "Thin", ["Fat", "Big", "Wide"]),
    ("Alive", "Dead", ["Living", "Real", "Life"]),
    ("Boy", "Girl", ["Man", "Woman", "Kid"]),
    ("Man", "Woman", ["Boy", "Girl", "Guy"]),
    ("Brother", "Sister", ["Did", "Mom", "Friend"]),
    ("Sun", "Moon", ["Star", "Sky", "Light"])
]

# --- SPELLING L1 (55 items) ---
spelling_l1 = [
    ("Because", ["Becuse", "Beacuse", "Becuase"]),
    ("Friend", ["Freind", "Frend", "Frind"]),
    ("School", ["Skool", "Schoal", "Shool"]),
    ("Teacher", ["Teecher", "Techer", "Teachir"]),
    ("House", ["Howse", "Hous", "Hoose"]),
    ("Please", ["Pleese", "Plese", "Pleaze"]),
    ("Animal", ["Aminal", "Animul", "Anamal"]),
    ("Mother", ["Muther", "Mather", "Mothur"]),
    ("Father", ["Fether", "Fathar", "Futher"]),
    ("Orange", ["Ornge", "Orang", "Orenge"]),
    ("Yellow", ["Yelow", "Yellowe", "Yellwo"]),
    ("Purple", ["Perple", "Purpel", "Purpule"]),
    ("Doctor", ["Docter", "Docktor", "Doktor"]),
    ("Little", ["Litel", "Littlb", "Littel"]),
    ("People", ["Peple", "Peopol", "Poeple"]),
    ("Happy", ["Hapy", "Happey", "Hapey"]),
    ("Pretty", ["Prety", "Prettie", "Prity"]),
    ("Family", ["Famaly", "Famely", "Fammily"]),
    ("Rabbit", ["Rabit", "Rabbet", "Rabbiit"]),
    ("Summer", ["Sumer", "Summur", "Summr"]),
    ("Winter", ["Wintr", "Wintar", "Wintre"]),
    ("Spring", ["Sring", "Sping", "Spreng"]),
    ("Garden", ["Gardan", "Gardin", "Gardon"]),
    ("Flower", ["Flowr", "Flowar", "Flour"]),
    ("Letter", ["Leter", "Lettur", "Lettr"]),
    ("Number", ["Numbr", "Numbur", "Numbar"]),
    ("Sister", ["Sistr", "Sistar", "Sistor"]),
    ("Brother", ["Bruther", "Brothr", "Brothar"]),
    ("Window", ["Windo", "Windwo", "Windw"]),
    ("Picture", ["Pictr", "Pikture", "Pitcher"]),
    ("Morning", ["Mornin", "Morneing", "Marning"]),
    ("Ground", ["Grownd", "Grund", "Graund"]),
    ("Listen", ["Lisen", "Listin", "Lissen"]),
    ("Table", ["Tabel", "Tabul", "Tuble"]),
    ("Chair", ["Chare", "Cair", "Cheir"]),
    ("Phone", ["Fone", "Phoen", "Phon"]),
    ("Watch", ["Wach", "Wotch", "Watsh"]),
    ("Water", ["Watter", "Watar", "Wotr"]),
    ("Clock", ["Clok", "Clook", "Cloc"]),
    ("Apple", ["Aple", "Appel", "Apel"]),
    ("Banana", ["Bananna", "Bannana", "Banena"]),
    ("Grapes", ["Grapps", "Graps", "Greps"]),
    ("Carrot", ["Carot", "Carrat", "Cerrot"]),
    ("Pizza", ["Piza", "Peatza", "Pizzah"]),
    ("Burger", ["Berger", "Burgur", "Burgr"]),
    ("Candy", ["Cany", "Candey", "Kandy"]),
    ("Puppy", ["Pupy", "Popwy", "Puppie"]),
    ("Kitten", ["Kiten", "Kittin", "Kittan"]),
    ("Bird", ["Burd", "Birde", "Byrd"]),
    ("Fish", ["Fsh", "Fisch", "Phish"]),
    ("Train", ["Trane", "Tran", "Traine"]),
    ("Truck", ["Truk", "Truc", "Truch"]),
    ("Plane", ["Plain", "Plaine", "Plan"]),
    ("Boat", ["Bote", "Bot", "Boate"])
]

# --- GRAMMAR L1 (55 items) ---
grammar_l1 = [
    ("I ___ to the store yesterday.", "went", ["go", "gone", "going"]),
    ("She ___ a beautiful song.", "sang", ["sing", "sung", "singed"]),
    ("They ___ playing football.", "are", ["is", "am", "was"]),
    ("He ___ his homework now.", "is doing", ["did", "done", "do"]),
    ("We ___ lunch at 1 PM.", "eat", ["eats", "ate", "eating"]),
    ("The cat ___ on the mat.", "sat", ["sit", "sited", "sitting"]),
    ("___ you like ice cream?", "Do", ["Does", "Are", "Is"]),
    ("She ___ not like apples.", "does", ["do", "is", "are"]),
    ("I have ___ interesting book.", "an", ["a", "the", "two"]),
    ("The sun ___ in the east.", "rises", ["rise", "rose", "rising"]),
    ("They ___ happy to see us.", "were", ["was", "is", "be"]),
    ("___ is your name?", "What", ["Who", "Where", "When"]),
    ("___ old are you?", "How", ["Who", "What", "When"]),
    ("My brother ___ taller than me.", "is", ["are", "am", "be"]),
    ("We ___ to the park last Sunday.", "went", ["go", "goes", "gone"]),
    ("Please ___ the door.", "close", ["closed", "closing", "closes"]),
    ("I ___ reading a book.", "am", ["is", "are", "be"]),
    ("The dogs ___ barking loudly.", "are", ["is", "was", "am"]),
    ("She ___ a new car.", "has", ["have", "having", "had"]),
    ("I ___ see the bird.", "can", ["am", "is", "are"]),
    ("Lets ___ for a walk.", "go", ["went", "gone", "going"]),
    ("She is ___ than her sister.", "taller", ["tall", "tallest", "more tall"]),
    ("This is the ___ day of my life.", "best", ["good", "better", "goodest"]),
    ("He ran ___.", "quickly", ["quick", "fastness", "quicker"]),
    ("The sky is ___.", "blue", ["blew", "blow", "blues"]),
    ("I ___ an apple.", "ate", ["eat", "eaten", "eating"]),
    ("We ___ friends.", "are", ["is", "am", "be"]),
    ("It ___ raining today.", "is", ["are", "am", "be"]),
    ("___ you happy?", "Are", ["Is", "Am", "Do"]),
    ("She ___ to school by bus.", "goes", ["go", "going", "gone"]),
    ("I want to ___ a game.", "play", ["playing", "played", "plays"]),
    ("Can I ___ some water?", "have", ["has", "had", "having"]),
    ("Look ___ the sky.", "at", ["on", "in", "to"]),
    ("Put the book ___ the table.", "on", ["in", "at", "to"]),
    ("My shoes are ___ the bed.", "under", ["over", "up", "between"]),
    ("The bird is ___ the tree.", "in", ["on", "at", "to"]),
    ("I am ___ years old.", "ten", ["tent", "teen", "tin"]),
    ("He has ___ legs.", "two", ["to", "too", "tow"]),
    ("I see with my ___.", "eyes", ["ears", "nose", "mouth"]),
    ("I hear with my ___.", "ears", ["eyes", "nose", "mouth"]),
    ("I smell with my ___.", "nose", ["ears", "eyes", "mouth"]),
    ("I walk with my ___.", "legs", ["hands", "arms", "head"]),
    ("I hold with my ___.", "hands", ["feet", "toes", "legs"]),
    ("A dog says ___.", "woof", ["meow", "moo", "oink"]),
    ("A cat says ___.", "meow", ["woof", "moo", "oink"]),
    ("A cow says ___.", "moo", ["meow", "woof", "oink"]),
    ("Roses are ___.", "red", ["blue", "green", "black"]),
    ("Grass is ___.", "green", ["red", "blue", "yellow"]),
    ("The sky is ___.", "blue", ["green", "red", "yellow"]),
    ("Snow is ___.", "white", ["black", "red", "green"]),
    ("Coal is ___.", "black", ["white", "red", "green"]),
    ("Fire is ___.", "hot", ["cold", "cool", "wet"]),
    ("Ice is ___.", "cold", ["hot", "warm", "dry"]),
    ("A week has ___ days.", "seven", ["six", "five", "eight"]),
    ("A year has ___ months.", "twelve", ["ten", "eleven", "twenty"])
]

# PLACEHOLDERS FOR L2 AND L3 (Will be populated next)
synonyms_l2 = [
    ("Abundant", "Plentiful", ["Scarce", "Rare", "Few"]),
    ("Accurate", "Precise", ["Wrong", "Vague", "False"]),
    ("Admit", "Confess", ["Deny", "Hide", "Refuse"]),
    ("Aggressive", "Hostile", ["Friendly", "Peaceful", "Calm"]),
    ("Ambitious", "Aspiring", ["Lazy", "Content", "Simple"]),
    ("Anxious", "Nervous", ["Calm", "Confident", "Brave"]),
    ("Apparent", "Obvious", ["Hidden", "Secret", "Unclear"]),
    ("Arrogant", "Haughty", ["Humble", "Modest", "Shy"]),
    ("Artificial", "Fake", ["Real", "Natural", "Genuine"]),
    ("Astonish", "Amaze", ["Bore", "Expect", "Calm"]),
    ("Awful", "Terrible", ["Wonderful", "Good", "Nice"]),
    ("Awkward", "Clumsy", ["Graceful", "Skillful", "Easy"]),
    ("Ban", "Prohibit", ["Allow", "Permit", "Let"]),
    ("Barren", "Empty", ["Fertile", "Full", "Rich"]),
    ("Beneficial", "Helpful", ["Harmful", "Bad", "Useless"]),
    ("Blend", "Mix", ["Separate", "Divide", "Isolate"]),
    ("Blunt", "Dull", ["Sharp", "Pointed", "Smart"]),
    ("Brisk", "Fast", ["Slow", "Lazy", "Quiet"]),
    ("Candid", "Honest", ["Deceitful", "Lying", "Fake"]),
    ("Cautious", "Careful", ["Reckless", "Wild", "Brave"]),
    ("Cease", "Stop", ["Begin", "Start", "Continue"]),
    ("Chaos", "Disorder", ["Order", "Peace", "Calm"]),
    ("Collapse", "Fall", ["Rise", "Stand", "Build"]),
    ("Commence", "Start", ["End", "Finish", "Stop"]),
    ("Competent", "Capable", ["Useless", "Weak", "Stupid"]),
    ("Complex", "Complicated", ["Simple", "Easy", "Basic"]),
    ("Comply", "Obey", ["Refuse", "Ignore", "Fight"]),
    ("Conceal", "Hide", ["Reveal", "Show", "Tell"]),
    ("Confine", "Restrict", ["Free", "Release", "Open"]),
    ("Conflict", "Fight", ["Peace", "Agreement", "Calm"]),
    ("Consent", "Agree", ["Refuse", "Deny", "Hate"]),
    ("Considerate", "Thoughtful", ["Selfish", "Rude", "Mean"]),
    ("Constant", "Steady", ["Changing", "Broken", "Rare"]),
    ("Contaminate", "Pollute", ["Clean", "Purify", "Fix"]),
    ("Contradict", "Deny", ["Agree", "Confirm", "Support"]),
    ("Courteous", "Polite", ["Rude", "Mean", "Rough"]),
    ("Deduce", "Infer", ["Guess", "Ignore", "Ask"]),
    ("Defend", "Protect", ["Attack", "Harm", "Kill"]),
    ("Defy", "Resist", ["Obey", "Follow", "Agree"]),
    ("Delicate", "Fragile", ["Strong", "Tough", "Hard"]),
    ("Diminish", "Decrease", ["Increase", "Grow", "Add"]),
    ("Disaster", "Calamity", ["Success", "Luck", "Joy"]),
    ("Distinct", "Clear", ["Vague", "Blurry", "Same"]),
    ("Diverse", "Varied", ["Same", "Similar", "Uniform"]),
    ("Domestic", "Native", ["Foreign", "Alien", "Wild"]),
    ("Dormant", "Inactive", ["Active", "Busy", "Alive"]),
    ("Dreadful", "Terrible", ["Nice", "Good", "Great"]),
    ("Durable", "Strong", ["Weak", "Soft", "Fragile"]),
    ("Eager", "Keen", ["Bored", "Lazy", "Slow"]),
    ("Economical", "Cheap", ["Expensive", "Costly", "Rich"]),
    ("Elaborate", "Detailed", ["Simple", "Plain", "Brief"]),
    ("Eligible", "Qualified", ["Unfit", "Bad", "Wrong"]),
    ("Emit", "Release", ["Keep", "Hold", "Take"]),
    ("Enormous", "Huge", ["Tiny", "Small", "Mini"]),
    ("Evaluate", "Assess", ["Ignore", "Guess", "Miss"])
]
antonyms_l2 = [
    ("Ability", "Inability", ["Power", "Skill", "Talent"]),
    ("Abnormal", "Normal", ["Crazy", "Wild", "Weird"]),
    ("Abolish", "Create", ["Destroy", "End", "Stop"]),
    ("Abundance", "Scarcity", ["Plenty", "Lot", "Many"]),
    ("Accidental", "Intentional", ["Chance", "Lucky", "Fate"]),
    ("Active", "Passive", ["Busy", "Fast", "Go"]),
    ("Add", "Subtract", ["Plus", "More", "Sum"]),
    ("Admit", "Deny", ["Tell", "Say", "Speak"]),
    ("Adult", "Child", ["Man", "Woman", "Old"]),
    ("Advance", "Retreat", ["Go", "Move", "Run"]),
    ("Advantage", "Disadvantage", ["Good", "Better", "Best"]),
    ("Affirm", "Deny", ["Say", "Tell", "Speak"]),
    ("Agree", "Disagree", ["Yes", "No", "Maybe"]),
    ("Ally", "Enemy", ["Friend", "Pal", "Mate"]),
    ("Amateur", "Professional", ["Novice", "New", "Bad"]),
    ("Amuse", "Bore", ["Fun", "Joke", "Laugh"]),
    ("Ancestor", "Descendant", ["Father", "Mother", "Old"]),
    ("Angel", "Devil", ["God", "Good", "Saint"]),
    ("Apart", "Together", ["Split", "Cut", "Divide"]),
    ("Apparent", "Obscure", ["Clear", "Plain", "See"]),
    ("Approach", "Depart", ["Come", "Near", "Go"]),
    ("Argue", "Agree", ["Fight", "War", "Battle"]),
    ("Arrival", "Departure", ["Come", "Here", "Now"]),
    ("Arrogant", "Humble", ["Proud", "Vain", "Mean"]),
    ("Ascend", "Descend", ["Up", "High", "Climb"]),
    ("Attack", "Defend", ["Hit", "Punch", "Kick"]),
    ("Attract", "Repel", ["Pull", "Draw", "Like"]),
    ("Awake", "Asleep", ["Up", "Rise", "Stand"]),
    ("Backward", "Forward", ["Back", "Behind", "Rear"]),
    ("Beautiful", "Ugly", ["Pretty", "Nice", "Good"]),
    ("Beginning", "Ending", ["Start", "First", "Open"]),
    ("Better", "Worse", ["Good", "Best", "Fine"]),
    ("Big", "Little", ["Huge", "Large", "Giant"]),
    ("Birth", "Death", ["Life", "Live", "Born"]),
    ("Bitter", "Sweet", ["Sour", "Bad", "Hot"]),
    ("Blame", "Praise", ["Hate", "Mad", "Angry"]),
    ("Bless", "Curse", ["Pray", "God", "Good"]),
    ("Bold", "Timid", ["Brave", "Strong", "Hard"]),
    ("Borrow", "Lend", ["Take", "Get", "Have"]),
    ("Bottom", "Top", ["Low", "Down", "Under"]),
    ("Break", "Mend", ["Smash", "Cut", "Kill"]),
    ("Brief", "Long", ["Short", "Quick", "Small"]),
    ("Bright", "Dull", ["Shiny", "Light", "Sun"]),
    ("Broad", "Narrow", ["Wide", "Big", "Fat"]),
    ("Build", "Destroy", ["Make", "Fix", "Create"]),
    ("Busy", "Lazy", ["Work", "Fast", "Hard"]),
    ("Calm", "Windy", ["Quiet", "Still", "Peace"]),
    ("Captive", "Free", ["Held", "Bound", "Tied"]),
    ("Capture", "Release", ["Take", "Get", "Hold"]),
    ("Careful", "Careless", ["Safe", "Sure", "Good"]),
    ("Cheap", "Expensive", ["Low", "Cost", "Price"]),
    ("Clean", "Dirty", ["Pure", "Neat", "Nice"]),
    ("Clever", "Stupid", ["Smart", "Bright", "Sharp"]),
    ("Cloudy", "Sunny", ["Rain", "Dark", "Grey"]),
    ("Cold", "Hot", ["Cool", "Warm", "Ice"])
]
spelling_l2 = [
    ("Accident", ["Acident", "Accidant", "Axident"]),
    ("Address", ["Adress", "Addres", "Adresss"]),
    ("Believe", ["Beleive", "Belive", "Byleive"]),
    ("Bicycle", ["Bycicle", "Biscyle", "Bicyle"]),
    ("Calendar", ["Calender", "Calander", "Celendar"]),
    ("Library", ["Liberry", "Libary", "Librery"]),
    ("Minute", ["Minite", "Minut", "Menute"]),
    ("Neighbor", ["Nieghbor", "Naybor", "Neigbor"]),
    ("Notice", ["Notise", "Notice", "Notic"]),
    ("Occasion", ["Ocasion", "Occason", "Occassion"]),
    ("Opposite", ["Oposite", "Oppossite", "Oposet"]),
    ("Original", ["Orignal", "Origonal", "Orginial"]),
    ("Parallel", ["Paralel", "Parrallel", "Parallell"]),
    ("Pattern", ["Patern", "Patturn", "Patten"]),
    ("Perhaps", ["Prehaps", "Perhapes", "Peraps"]),
    ("Pleasant", ["Plesant", "Pleasent", "Plesent"]),
    ("Possible", ["Posible", "Possable", "Possibal"]),
    ("Potatoes", ["Potatos", "Patatoes", "Potatoze"]),
    ("Probably", ["Probly", "Probobly", "Probabaly"]),
    ("Problem", ["Problum", "Problam", "Prblem"]),
    ("Promise", ["Promis", "Promiss", "Prmise"]),
    ("Quarter", ["Qarter", "Kwarter", "Quater"]),
    ("Quietly", ["Quietley", "Quietely", "Queitly"]),
    ("Receive", ["Recieve", "Receve", "Reiceve"]),
    ("Recommend", ["Recomend", "Reccomend", "Reccommend"]),
    ("Restaurant", ["Restraght", "Restarant", "Restaraunt"]),
    ("Rhythm", ["Rythm", "Rithm", "Rhythem"]),
    ("Saturday", ["Saterday", "Saturdy", "Saterdy"]),
    ("Schedule", ["Schedual", "Scdule", "Skedule"]),
    ("Separate", ["Seperate", "Sepparate", "Seprate"]),
    ("Special", ["Speshul", "Specail", "Specal"]),
    ("Stomach", ["Stomack", "Stumach", "Stomache"]),
    ("Success", ["Sucess", "Succes", "Suksess"]),
    ("Surprise", ["Suprise", "Surpize", "Surprize"]),
    ("Telephone", ["Tellphone", "Telefone", "Telphone"]),
    ("Tomorrow", ["Tomorow", "Tommorrow", "Tommoro"]),
    ("Traffic", ["Trafic", "Traffic", "Traffick"]),
    ("Trouble", ["Truble", "Troubel", "Trobble"]),
    ("Tuesday", ["Tuseday", "Teusday", "Tusday"]),
    ("Usually", ["Usualy", "Usally", "Ushually"]),
    ("Vaccine", ["Vacine", "Vasine", "Vaxine"]),
    ("Vegetable", ["Vegtable", "Vegetubel", "Vegeatable"]),
    ("Vehicle", ["Vehical", "Vheicle", "Vecihle"]),
    ("Village", ["Billage", "Vilage", "Villege"]),
    ("Wednesday", ["Wensday", "Wednesdy", "Wenesday"]),
    ("Weight", ["Wheight", "Wieght", "Wate"]),
    ("Weird", ["Wierd", "Wird", "Weiyrd"]),
    ("Whistle", ["Wistle", "Whisel", "Whistal"]),
    ("Yellow", ["Yelow", "Yellwo", "Yello"]),
    ("Yesterday", ["Yesturday", "Yesteday", "Yisterday"]),
    ("Young", ["Yung", "Yonug", "Yang"])
]
grammar_l2 = [
    ("I have ___ seen that movie.", "already", ["yet", "still", "now"]),
    ("She is interested ___ learning French.", "in", ["on", "at", "for"]),
    ("He is good ___ playing chess.", "at", ["in", "on", "with"]),
    ("They have lived here ___ 2010.", "since", ["for", "from", "ago"]),
    ("I have been waiting ___ two hours.", "for", ["since", "from", "during"]),
    ("If it rains, we ___ inside.", "will stay", ["stay", "stayed", "staying"]),
    ("Unless you study, you ___ fail.", "will", ["won't", "don't", "didn't"]),
    ("The book ___ by J.K. Rowling.", "was written", ["wrote", "writes", "writing"]),
    ("He asked me where I ___.", "lived", ["live", "living", "lives"]),
    ("She said she ___ busy.", "was", ["is", "are", "were"]),
    ("I prefer tea ___ coffee.", "to", ["than", "from", "over"]),
    ("He works ___ a doctor.", "as", ["like", "so", "such"]),
    ("You look ___ your mother.", "like", ["as", "same", "similar"]),
    ("The police ___ investigating the crime.", "are", ["is", "was", "has"]),
    ("Neither of them ___ correct.", "is", ["are", "were", "have"]),
    ("Everyone ___ to be happy.", "wants", ["want", "wanting", "wills"]),
    ("The news ___ good.", "is", ["are", "were", "have"]),
    ("Mathematics ___ my favorite subject.", "is", ["are", "were", "have"]),
    ("I wish I ___ a bird.", "were", ["was", "am", "is"]),
    ("He behaves as if he ___ the boss.", "were", ["was", "is", "are"]),
    ("It is time we ___ home.", "went", ["go", "gone", "going"]),
    ("I would rather ___ home.", "stay", ["to stay", "staying", "stayed"]),
    ("You had better ___ a doctor.", "see", ["to see", "seeing", "saw"]),
    ("I look forward to ___ you.", "meeting", ["meet", "met", "meets"]),
    ("She is used to ___ early.", "waking", ["wake", "woke", "waken"]),
    ("Despite ___ hard, he failed.", "working", ["work", "worked", "works"]),
    ("Although he was ill, ___ he went to work.", "yet", ["but", "and", "so"]),
    ("No sooner did he arrive ___ it started raining.", "than", ["when", "then", "that"]),
    ("Hardly had I left ___ it began to snow.", "when", ["than", "then", "that"]),
    ("Not only Alice ___ also Bob passed.", "but", ["and", "or", "so"]),
    ("The soup tastes ___.", "good", ["well", "finely", "best"]),
    ("He drives ___.", "carefully", ["careful", "good", "fastly"]),
    ("She speaks English ___.", "fluently", ["fluent", "good", "easy"]),
    ("I am ___ tired.", "very", ["too", "much", "many"]),
    ("He is ___ weak to walk.", "too", ["very", "so", "much"]),
    ("She is ___ smart.", "so", ["such", "too", "much"]),
    ("It was ___ a lovely day.", "such", ["so", "too", "very"]),
    ("None of the boys ___ here.", "is", ["are", "were", "has"]),
    ("Each of the girls ___ a doll.", "has", ["have", "having", "had"]),
    ("Either John or Mary ___ coming.", "is", ["are", "were", "have"]),
    ("Neither the teacher nor the students ___ here.", "are", ["is", "was", "has"]),
    ("My family ___ going on a trip.", "is", ["are", "were", "have"]),
    ("The team ___ winning.", "is", ["are", "were", "have"]),
    ("Start ___ the beginning.", "at", ["in", "on", "to"]),
    ("He jumped ___ the river.", "into", ["in", "on", "at"]),
    ("She walked ___ the room.", "into", ["in", "on", "at"]),
    ("The cat jumped ___ the table.", "off", ["of", "from", "out"]),
    ("He is sitting ___ me.", "beside", ["besides", "next", "near"]),
    ("Besides English, he speaks French.", "Besides", ["Beside", "Next", "Near"]),
    ("Between you and ___.", "me", ["I", "myself", "mine"])
]

synonyms_l3 = [
    ("Acquiesce", "Agree", ["Resist", "Protest", "Argue"]),
    ("Acrimonious", "Bitter", ["Sweet", "Nice", "Friendly"]),
    ("Adversity", "Hardship", ["Luck", "Joy", "Ease"]),
    ("Aesthetic", "Artistic", ["Ugly", "Plain", "Boring"]),
    ("Alleviate", "Relieve", ["Worsen", "Agitate", "Hurt"]),
    ("Ambiguous", "Unclear", ["Clear", "Certain", "Definite"]),
    ("Ambivalent", "Uncertain", ["Sure", "Decided", "Happy"]),
    ("Ameliorate", "Improve", ["Worsen", "Ruin", "Break"]),
    ("Anachronistic", "Outdated", ["Modern", "New", "Fresh"]),
    ("Anomaly", "Irregularity", ["Norm", "Standard", "Rule"]),
    ("Antipathy", "Dislike", ["Love", "Friendship", "Like"]),
    ("Apathy", "Indifference", ["Care", "Passion", "Interest"]),
    ("Appease", "Soothe", ["Anger", "Provoke", "Annoy"]),
    ("Apprehensive", "Anxious", ["Confident", "Calm", "Brave"]),
    ("Articulate", "Expressive", ["Mute", "Silent", "Unclear"]),
    ("Ascertain", "Determine", ["Guess", "Ignore", "Miss"]),
    ("Assiduous", "Diligent", ["Lazy", "Careless", "Slow"]),
    ("Astute", "Shrewd", ["Stupid", "Naive", "Blind"]),
    ("Audacious", "Bold", ["Timis", "Scared", "Weak"]),
    ("Augment", "Increase", ["Decrease", "Reduce", "Cut"]),
    ("Austere", "Severe", ["Gentle", "Soft", "Kind"]),
    ("Authentic", "Genuine", ["Fake", "False", "Copy"]),
    ("Benevolent", "Kind", ["Cruel", "Mean", "Evil"]),
    ("Benign", "Harmless", ["Harmful", "Bad", "Fatal"]),
    ("Boisterous", "Noisy", ["Quiet", "Calm", "Silent"]),
    ("Brevity", "Briefness", ["Length", "Size", "Depth"]),
    ("Candid", "Frank", ["Secret", "Lying", "False"]),
    ("Capricious", "Unpredictable", ["Steady", "Constant", "Sure"]),
    ("Censure", "Criticize", ["Praise", "Love", "Help"]),
    ("Cognizant", "Aware", ["Ignorant", "Blind", "Lost"]),
    ("Coherent", "Logical", ["Crazy", "Messy", "Wild"]),
    ("Complacent", "Satisfied", ["Worried", "Anxious", "Sad"]),
    ("Compliance", "Obedience", ["Rebellion", "Fight", "War"]),
    ("Concise", "Brief", ["Long", "Wordy", "Huge"]),
    ("Condone", "Forgive", ["Punish", "Hate", "Stop"]),
    ("Conspicuous", "Noticeable", ["Hidden", "Invisible", "Lost"]),
    ("Contempt", "Scorn", ["Respect", "Love", "Care"]),
    ("Copious", "Abundant", ["Scarce", "Rare", "Few"]),
    ("Corroborate", "Confirm", ["Deny", "Reject", "Lie"]),
    ("Cursory", "Hasty", ["Thorough", "Slow", "Deep"]),
    ("Debilitate", "Weaken", ["Strengthen", "Help", "Cure"]),
    ("Decorous", "Polite", ["Rude", "Wild", "Bad"]),
    ("Deference", "Respect", ["Disrespect", "Hate", "Scorn"]),
    ("Deleterious", "Harmful", ["Helpful", "Good", "Safe"]),
    ("Delineate", "Describe", ["Confuse", "Hide", "Mix"]),
    ("Despondent", "Sad", ["Happy", "Joyful", "Glad"]),
    ("Despise", "Hate", ["Love", "Like", "Care"]),
    ("Detrimental", "Harmful", ["Good", "Nice", "Safe"]),
    ("Deviate", "Stray", ["Stay", "Keep", "Follow"]),
    ("Diffident", "Shy", ["Bold", "Brave", "Loud"]),
    ("Diligent", "Hardworking", ["Lazy", "Slow", "Bad"]),
    ("Diminish", "Reduce", ["Increase", "Add", "Grow"]),
    ("Discern", "Perceive", ["Ignore", "Miss", "Lose"]),
    ("Discord", "Conflict", ["Peace", "Harmony", "Love"]),
    ("Disdain", "Scorn", ["Respect", "Love", "Care"])
]
antonyms_l3 = [
    ("Abate", "Increase", ["Stop", "End", "Finish"]),
    ("Abbreviate", "Lengthen", ["Shorten", "Cut", "End"]),
    ("Abhor", "Love", ["Hate", "Dislike", "Scorn"]),
    ("Abridge", "Expand", ["Cut", "Shorten", "End"]),
    ("Absolve", "Blame", ["Free", "Forgive", "Clear"]),
    ("Absurd", "Rational", ["Silly", "Crazy", "Mad"]),
    ("Abundant", "Scarce", ["Many", "Lot", "Full"]),
    ("Accelerate", "Decelerate", ["Fast", "Speed", "Go"]),
    ("Accord", "Discord", ["Peace", "Love", "Unity"]),
    ("Acquit", "Convict", ["Free", "Clear", "Let go"]),
    ("Acute", "Obtuse", ["Sharp", "Smart", "Quick"]),
    ("Adamant", "Flexible", ["Hard", "Firm", "Set"]),
    ("Adversity", "Prosperity", ["Bad", "Luck", "Fate"]),
    ("Affluent", "Poor", ["Rich", "Wealthy", "Money"]),
    ("Aggravate", "Soothe", ["Worsen", "Bad", "Mad"]),
    ("Alleviate", "Aggravate", ["Help", "Fix", "Cure"]),
    ("Aloof", "Friendly", ["Cold", "Distant", "Far"]),
    ("Altruistic", "Selfish", ["Kind", "Good", "Nice"]),
    ("Ambiguous", "Clear", ["Vague", "Dark", "Dim"]),
    ("Ameliorate", "Worsen", ["Better", "Fix", "Good"]),
    ("Amiable", "Hostile", ["Nice", "Kind", "Good"]),
    ("Amplify", "Reduce", ["Loud", "Big", "More"]),
    ("Ancestor", "Descendant", ["Old", "Past", "Dead"]),
    ("Ancient", "Modern", ["Old", "Past", "Age"]),
    ("Anonymous", "Named", ["Unknown", "Secret", "Hid"]),
    ("Antapathy", "Sympathy", ["Hate", "Mad", "Bad"]),
    ("Apathy", "Concern", ["Care", "Love", "Like"]),
    ("Appease", "Provoke", ["Calm", "Peace", "Quiet"]),
    ("Arduous", "Easy", ["Hard", "Tough", "Work"]),
    ("Arid", "Fertile", ["Dry", "Hot", "Sand"]),
    ("Artificial", "Natural", ["Fake", "False", "Copy"]),
    ("Ascend", "Descend", ["Up", "Rise", "Climb"]),
    ("Assent", "Dissent", ["Yes", "Agree", "Nod"]),
    ("Assuage", "Irritate", ["Calm", "Help", "Fix"]),
    ("Astute", "Foolish", ["Smart", "Sharp", "Quick"]),
    ("Atrophy", "Growth", ["Rot", "Die", "End"]),
    ("Attain", "Lose", ["Get", "Win", "Have"]),
    ("Audacious", "Cautions", ["Bold", "Brave", "Wild"]),
    ("Augment", "Decrease", ["Add", "More", "Plus"]),
    ("Authentic", "Fake", ["Real", "True", "Good"]),
    ("Autonomy", "Dependence", ["Free", "Self", "Rule"]),
    ("Aversion", "Liking", ["Hate", "Dislike", "Mad"]),
    ("Banal", "Original", ["Boring", "Plain", "Dull"]),
    ("Barren", "Fetile", ["Empty", "Dry", "Dead"]),
    ("Bashful", "Bold", ["Shy", "Quiet", "Timis"]),
    ("Beautiful", "Grotesque", ["Pretty", "Nice", "Good"]),
    ("Belligerent", "Peaceful", ["Mad", "Angry", "Mean"]),
    ("Benevolent", "Malevolent", ["Kind", "Good", "Nice"]),
    ("Benign", "Malignant", ["Safe", "Good", "Fine"]),
    ("Best", "Worst", ["Good", "Better", "Bad"]),
    ("Bind", "Release", ["Tie", "Hold", "Keep"]),
    ("Bitter", "Sweet", ["Sour", "Bad", "Hot"]),
    ("Blank", "Full", ["Empty", "White", "Clear"]),
    ("Blend", "Separate", ["Mix", "Stir", "Fix"]),
    ("Bless", "Curse", ["Pray", "God", "Good"])
]
spelling_l3 = [
    ("Accommodate", ["Acommodate", "Accomodate", "Acomodate"]),
    ("Acquaintance", ["Aquaintance", "Acquantance", "Acquaintence"]),
    ("Acquire", ["Aquire", "Acqire", "Aquyer"]),
    ("Amateur", ["Amatuer", "Amature", "Ameteur"]),
    ("Apparent", ["Apparant", "Aparent", "Apparrent"]),
    ("Argument", ["Arguement", "Argumant", "Arguemint"]),
    ("Atheist", ["Athiest", "Athist", "Atheyist"]),
    ("Believe", ["Beleive", "Belive", "Byleive"]),
    ("Caribbean", ["Carribean", "Carribbean", "Caribean"]),
    ("Cemetery", ["Cemetary", "Cemmetery", "Cematary"]),
    ("Changeable", ["Changable", "Changeble", "Changabel"]),
    ("Collectible", ["Collectable", "Collectibel", "Colectible"]),
    ("Column", ["Colum", "Collumn", "Colomn"]),
    ("Committed", ["Commited", "Comitted", "Comited"]),
    ("Conscience", ["Conscience", "Conscence", "Consceince"]),
    ("Conscious", ["Concious", "Consious", "Conscius"]),
    ("Consensus", ["Concensus", "Consenssus", "Concenus"]),
    ("Daiquiri", ["Daquiri", "Daikiri", "Daiquiry"]),
    ("Definite", ["Definate", "Definit", "Defonite"]),
    ("Discipline", ["Disipline", "Disipline", "Decipline"]),
    ("Drunkenness", ["Drunkeness", "Drunkness", "Drunknness"]),
    ("Embarrass", ["Embarass", "Emberrass", "Embaras"]),
    ("Equipment", ["Equipmant", "Equipmint", "Equippment"]),
    ("Exhilarate", ["Exhilerate", "Exilarate", "Exhilarat"]),
    ("Exceed", ["Excede", "Xceed", "Excead"]),
    ("Existence", ["Existance", "Existans", "Existenze"]),
    ("Experience", ["Experiance", "Experanse", "Experiense"]),
    ("Fiery", ["Firey", "Fierrie", "Fierey"]),
    ("Foreign", ["Foriegn", "Forein", "Forreign"]),
    ("Gauge", ["Guage", "Gage", "Gauje"]),
    ("Grateful", ["Greatful", "Gratefull", "Greatfull"]),
    ("Guarantee", ["Garantee", "Guaranty", "Garauntee"]),
    ("Harass", ["Harrass", "Haras", "Harrasz"]),
    ("Height", ["Hieght", "Heighth", "Hight"]),
    ("Hierarchy", ["Hierarcy", "Hiarchy", "Hierachy"]),
    ("Humorous", ["Humourous", "Humerous", "Humoros"]),
    ("Ignorance", ["Ignorence", "Ignorense", "Ignoranze"]),
    ("Immediate", ["Immediat", "Imediate", "Immedite"]),
    ("Independent", ["Independant", "Indipendent", "Independet"]),
    ("Intelligence", ["Inteligence", "Intelligance", "Inteligenze"]),
    ("Jewelry", ["Jewelery", "Jewlery", "Jewllery"]),
    ("Judgment", ["Judgement", "Judgmant", "Jugment"]),
    ("Kernel", ["Kernal", "Cernel", "Colnel"]),
    ("Leisure", ["Liesure", "Lesure", "Leasure"]),
    ("Liaison", ["Liason", "Liasion", "Laision"]),
    ("License", ["Lisence", "Licence", "Lisense"]),
    ("Maintenance", ["Maintainance", "Maintenence", "Maintanance"]),
    ("Maneuver", ["Maneuvre", "Manuever", "Manuver"]),
    ("Medieval", ["Medeval", "Medideval", "Mideval"]),
    ("Memento", ["Momento", "Mementto", "Momemto"]),
    ("Millennium", ["Millenium", "Milennium", "Milenium"]),
    ("Miniature", ["Miniture", "Miniateur", "Miniture"]),
    ("Minuscule", ["Miniscule", "Minuscool", "Minischool"]),
    ("Mischievous", ["Mischievious", "Mischevious", "Mishievous"])
]
grammar_l3 = [
    ("The jury ___ divided in their opinions.", "were", ["was", "is", "has"]),
    ("Either you or he ___ to blame.", "is", ["are", "were", "have"]),
    ("Many a man ___ done this.", "has", ["have", "are", "were"]),
    ("The number of students ___ increasing.", "is", ["are", "were", "have"]),
    ("A number of students ___ absent.", "are", ["is", "was", "has"]),
    ("Had I known, I ___ have come.", "would", ["will", "shall", "can"]),
    ("If I ___ you, I would accept.", "were", ["was", "am", "be"]),
    ("Lest you ___ fall, hold the rail.", "should", ["would", "could", "might"]),
    ("He speaks as though he ___ everything.", "knew", ["knows", "known", "knowing"]),
    ("It is essential that he ___ present.", "be", ["is", "was", "are"]),
    ("I suggest that she ___ the offer.", "accept", ["accepts", "accepted", "accepting"]),
    ("The rich ___ not always happy.", "are", ["is", "was", "has"]),
    ("Bread and butter ___ his daily food.", "is", ["are", "were", "have"]),
    ("Time and tide ___ for no man.", "wait", ["waits", "waiting", "waited"]),
    ("Creating a masterpiece requires ___ skill.", "great", ["big", "large", "huge"]),
    ("He is ___ to exaggerate.", "prone", ["apt", "likely", "possible"]),
    ("The data ___ accurate.", "is", ["are", "were", "be"]),
    ("Phenomena ___ mysterious.", "are", ["is", "was", "be"]),
    ("She is the ___ of the two sisters.", "older", ["oldest", "elder", "eldest"]),
    ("Whom did you speak ___?", "to", ["at", "on", "for"]),
    ("This connects the two, ___?", "doesn't it", ["don't it", "isn't it", "wasn't it"]),
    ("Neither the players nor the coach ___ expecting this.", "was", ["were", "are", "have"]),
    ("Between you and ___.", "me", ["I", "myself", "mine"]),
    ("He is taller than ___.", "I", ["me", "myself", "mine"]),
    ("It was ___ who called.", "she", ["her", "hers", "herself"]),
    ("Let ___ go.", "us", ["we", "our", "ourselves"]),
    ("Who do you think ___ is?", "he", ["him", "his", "himself"]),
    ("The man ___ I met yesterday is here.", "whom", ["who", "which", "that"]),
    ("One must keep ___ promise.", "one's", ["his", "her", "their"]),
    ("She is ___ university student.", "a", ["an", "the", "one"]),
    ("Physics ___ a difficult subject.", "is", ["are", "were", "have"]),
    ("Ten miles ___ a long long distance.", "is", ["are", "were", "have"]),
    ("The committee ___ issued its report.", "has", ["have", "are", "were"]),
    ("The committee ___ divided on this issue.", "are", ["is", "was", "has"]),
    ("He died ___ cancer.", "of", ["from", "by", "with"]),
    ("He died ___ thirst.", "from", ["of", "by", "with"]),
    ("I tired ___ wait.", "to", ["at", "of", "with"]),
    ("She is tired ___ waiting.", "of", ["from", "by", "with"]),
    ("He is angry ___ me.", "with", ["at", "on", "for"]),
    ("He is angry ___ my behavior.", "at", ["with", "on", "for"]),
    ("I differ ___ you on this point.", "with", ["from", "than", "to"]),
    ("This cloth differs ___ that.", "from", ["with", "than", "to"]),
    ("He deals ___ rice.", "in", ["with", "at", "on"]),
    ("He deals ___ everyone fairly.", "with", ["in", "at", "on"]),
    ("He is blind ___ one eye.", "in", ["of", "to", "with"]),
    ("He is blind ___ his son's faults.", "to", ["of", "in", "with"]),
    ("Compare this ___ that.", "with", ["to", "from", "of"]),
    ("He compared her face ___ the moon.", "to", ["with", "from", "of"]),
    ("I prefer walking ___ cycling.", "to", ["than", "from", "over"]),
    ("He is superior ___ me.", "to", ["than", "from", "of"]),
    ("Hard work is the key ___ success.", "to", ["of", "for", "in"]),
    ("He is married ___ a doctor.", "to", ["with", "by", "of"])
]


def generate_full_word_power():
    # Helper to generate quiz objects
    def create_qs(data, type_label, text_template, expl_template, difficulty, limit):
        qs = []
        random.shuffle(data)
        count = 0
        
        for item in data:
            if count >= limit: break
            
            # --- Logic by Type ---
            if type_label in ["Synonym", "Antonym"]:
                word, ans, dists = item
                text = text_template.format(word)
                expl = expl_template.format(word, ans)
                options = [ans] + dists
                
            elif type_label == "Spelling":
                correct, incorrects = item
                text = "Choose the correct spelling:"
                ans = correct
                dists = incorrects
                expl = f"'{correct}' is the correct spelling."
                options = [ans] + dists
            
            elif type_label == "Grammar":
                sent, ans, dists = item
                text = f"Fill in the blank:\n{sent}"
                expl = f"Correct answer: {ans}"
                options = [ans] + dists
            
            # Common Shuffle
            options = options[:4]
            random.shuffle(options)
            
            # We assign a temp ID here, but unique IDs are ensured in process()
            qs.append({
                "text": text,
                "options": options,
                "correctIndex": options.index(ans),
                "explanation": expl,
                "difficulty": difficulty
            })
            count += 1
        return qs

    def process(list_qs, prefix, limit=200):
        # Ensure deep unique copies
        final = []
        
        # If data is short and we need more, duplicate only once to avoid infinite loop
        if len(list_qs) < limit and len(list_qs) > 0:
            # Duplicate the list enough times to meet the limit
            times_needed = (limit // len(list_qs)) + 1
            original = copy.deepcopy(list_qs)
            for _ in range(times_needed - 1):
                list_qs.extend(copy.deepcopy(original))
        
        random.shuffle(list_qs)
        
        for i, q in enumerate(list_qs):
            if i >= limit: break
            new_q = copy.deepcopy(q)
            new_q["id"] = f"{prefix}_{i}"
            final.append(new_q)
        return final

    final_l1 = []
    final_l2 = []
    final_l3 = []
    
    # LEVEL 1 - extract ALL items
    final_l1.extend(create_qs(synonyms_l1, "Synonym", "Synonym of '{0}'?", "'{1}' is a synonym for '{0}'.", 1, 999))
    final_l1.extend(create_qs(antonyms_l1, "Antonym", "Antonym of '{0}'?", "'{1}' is the opposite of '{0}'.", 1, 999))
    final_l1.extend(create_qs(spelling_l1, "Spelling", "", "", 1, 999))
    final_l1.extend(create_qs(grammar_l1, "Grammar", "", "", 1, 999))
    
    # LEVEL 2 - extract ALL items
    final_l2.extend(create_qs(synonyms_l2, "Synonym", "Synonym of '{0}'?", "'{1}' means the same as '{0}'.", 2, 999))
    final_l2.extend(create_qs(antonyms_l2, "Antonym", "Antonym of '{0}'?", "'{1}' is the opposite of '{0}'.", 2, 999))
    final_l2.extend(create_qs(spelling_l2, "Spelling", "", "", 2, 999))
    final_l2.extend(create_qs(grammar_l2, "Grammar", "", "", 2, 999))
    
    # LEVEL 3 - extract ALL items
    final_l3.extend(create_qs(synonyms_l3, "Synonym", "Synonym of '{0}'?", "'{1}' closely matches '{0}'.", 3, 999))
    final_l3.extend(create_qs(antonyms_l3, "Antonym", "Antonym of '{0}'?", "'{1}' opposes '{0}'.", 3, 999))
    final_l3.extend(create_qs(spelling_l3, "Spelling", "", "", 3, 999))
    final_l3.extend(create_qs(grammar_l3, "Grammar", "", "", 3, 999))

    return {
        "id": "WORD_POWER",
        "name": "Word Power",
        "levels": [
            {"id": 1, "questions": process(final_l1, "wp_l1", 200)},
            {"id": 2, "questions": process(final_l2, "wp_l2", 200)},
            {"id": 3, "questions": process(final_l3, "wp_l3", 200)}
        ]
    }

if __name__ == "__main__":
    data = generate_full_word_power()
    with open('app/src/main/assets/word_power.json', 'w') as f:
        json.dump(data, f, indent=2)
    print("Word Power Generated.")
